version: '3.8'
services:
  user_service:
    container_name: user_service_container
    build: ./user-service
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./user-service:/app
      - /app/node_modules
    command: npx nodemon app.js
  workspace_service:
    container_name: workspace_service_container
    build: ./workspace-service
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./workspace-service:/app
      - /app/node_modules
    command: npx nodemon app.js
  channel_service:
    container_name: channel_service_container
    build: ./channel-service
    ports:
      - "3002:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./channel-service:/app
      - /app/node_modules
    command: npx nodemon app.js
  message_service:
    container_name: message_service_container
    build: ./message-service
    ports:
      - "3003:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./message-service:/app
      - /app/node_modules
    command: npx nodemon app.js
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
